// Generated by CoffeeScript 1.7.1
var combine, fs, inject_scripts, io, livereload, serve_livereload_file, server;

fs = require('fs');

io = void 0;

server = void 0;

combine = function(middlewares) {
  return function(req, res, next) {
    var iter;
    iter = function(i) {
      var middlware;
      middlware = middlewares[i];
      if (!middlware) {
        return next();
      }
      middlware(req, res, function(err) {
        if (err) {
          return next(err);
        }
        iter(i + 1);
      });
    };
    iter(0);
  };
};

serve_livereload_file = function(req, res, next) {
  if (req.url.indexOf('/combo-livereload.js') !== 0) {
    return next();
  } else {
    return fs.readFile(__dirname + '/combo-livereload.js', function(err, data) {
      if (err) {
        res.writeHead(500, err);
        return res.end(err);
      }
      return res.end(data);
    });
  }
};

inject_scripts = require('connect-inject')({
  snippet: "<script type='application/javascript' src='/socket.io/socket.io.js'></script>\n<script type='application/javascript' src='/combo-livereload.js'></script>"
});

livereload = module.exports = combine([serve_livereload_file, inject_scripts]);

livereload.listen = function(_server) {
  server = _server;
  return io = require('socket.io').listen(server, {
    log: false
  });
};

livereload.reloadImage = function(path) {
  return io.sockets.emit('reloadImage', path);
};
