// Generated by CoffeeScript 1.7.1
var fs, io, server;

fs = require('fs');

io = void 0;

server = void 0;

module.exports = {
  connect: function(_server) {
    server = _server;
    return io = require('socket.io').listen(server, {
      log: false
    });
  },
  reloadImage: function(path) {
    return io.sockets.emit('reloadImage', path);
  },
  middleware: require('connect-inject')({
    snippet: "<script type='application/javascript' src='/socket.io/socket.io.js'></script>\n<script type='application/javascript' src='/combo-livereload.js'></script>"
  }),
  'combo-livereload.js': function(req, res) {
    return fs.readFile(__dirname + '/plugin.js', function(err, data) {
      if (err) {
        res.writeHead(500, err);
        return res.end(err);
      }
      return res.end(data);
    });
  }
};
